name: instaflutter
description: Instaflutter Project
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  #icons
  cupertino_icons: 1.0.5

  #firebase packages
  firebase_core: 1.20.0
  firebase_storage: 10.3.3
  firebase_auth: 3.5.1
  firebase_messaging: 12.0.1
  cloud_functions: 3.3.3
  cloud_firestore: 3.4.1

  #state management
  flutter_riverpod: ^1.0.4
  #splash screen
  flutter_native_splash: 2.2.6

#splash screen
flutter_native_splash:
  image: assets/images/hug_me_logo.png
  color: "#61C9C3"
  color_dark: "#042a49"
  image_dark: assets/images/hug_me_logo.png
  android_12:
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true