// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR20qv7uGCjhVPSsJXUI6pGKNdoHUCdl4',
    appId: '1:185869155795:web:e7ca7512ce36ecdd408326',
    messagingSenderId: '185869155795',
    projectId: 'proteinsample',
    authDomain: 'proteinsample.firebaseapp.com',
    storageBucket: 'proteinsample.appspot.com',
    measurementId: 'G-NX5MLTESXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7DX3jQHv_7c_2pDZ7vn-iykbBTOESKag',
    appId: '1:185869155795:android:0e71197d7612f434408326',
    messagingSenderId: '185869155795',
    projectId: 'proteinsample',
    storageBucket: 'proteinsample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWy0Yq8poYrzAktq4nSsIITKhJfza4Mh4',
    appId: '1:185869155795:ios:f1679d5f81b2d390408326',
    messagingSenderId: '185869155795',
    projectId: 'proteinsample',
    storageBucket: 'proteinsample.appspot.com',
    iosClientId: '185869155795-809563h0ee4ki3hg4jgc0ball8ie09vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hugMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWy0Yq8poYrzAktq4nSsIITKhJfza4Mh4',
    appId: '1:185869155795:ios:f1679d5f81b2d390408326',
    messagingSenderId: '185869155795',
    projectId: 'proteinsample',
    storageBucket: 'proteinsample.appspot.com',
    iosClientId: '185869155795-809563h0ee4ki3hg4jgc0ball8ie09vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hugMe',
  );
}
